//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleExecutor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleExecutor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished: ofx file is at [{0}].
        /// </summary>
        internal static string ProgramMainComplete {
            get {
                return ResourceManager.GetString("ProgramMainComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;!-- saved from url=(0148)https://banking.smile.co.uk/SmileWeb/paginateDomesticStatement.do?paginate=next&amp;org.apache.struts.taglib.html.TOKEN=9743d94a0e04ccda66a1f09448f0df51 --&gt;
        ///&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot;&gt;
        ///    &lt;title&gt;
        ///       
        ///       Statements
        ///    &lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;./Page177_files/Master.css&quot; type=&quot;text/css&quot;&gt;
        ///	
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;no-cache&quot;&gt;
        ///	&lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShortSmileStatementSource {
            get {
                return ResourceManager.GetString("ShortSmileStatementSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;!-- saved from url=(0148)https://banking.smile.co.uk/SmileWeb/paginateDomesticStatement.do?paginate=next&amp;org.apache.struts.taglib.html.TOKEN=9743d94a0e04ccda66a1f09448f0df51 --&gt;
        ///&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot;&gt;
        ///    &lt;title&gt;
        ///       
        ///       Statements
        ///    &lt;/title&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;./Page177_files/Master.css&quot; type=&quot;text/css&quot;&gt;
        ///	
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;no-cache&quot;&gt;
        ///	&lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmileStatementSource {
            get {
                return ResourceManager.GetString("SmileStatementSource", resourceCulture);
            }
        }
    }
}
